[build]
  functions = "functions"
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_ENV = "production"

[context.branch-deploy]
  command = "npm run build-preview"
  publish = "dist-preview"